apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  type: ClusterIP
  selector:
    # app.kubernetes.io/name: app-three
    app: app-three
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080