
SERVER_NAME = "lpeggyS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "lpeggySW"
WORKER_IP =  "192.168.56.111"

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/xenial64"
	config.vm.provider :virtualbox do |v|
		v.customize [
			"modifyvm", :id,
			"--name", SERVER_NAME,
			"--cpus", "1",
			"--memory", "512"
		]
		end

	config.vm.define SERVER_NAME do |server|
		server.vm.hostname = SERVER_NAME
		server.vm.network :private_network, ip: SERVER_IP

		server.vm.provision :shell, inline: <<-SHELL
			echo "Server provisioned, starting server script"
		SHELL
		server.vm.provision "shell", path: "scripts/server.sh", args: [SERVER_IP]
	end

	# config.vm.define WORKER_NAME do |serverworker|
	# 	serverworker.vm.hostname = WORKER_NAME
	# 	serverworker.vm.network :private_network, ip: WORKER_IP

	# 	# config.vm.provision "shell", inline: <<-SHELL
	# 	serverworker.vm.provision "shell", inline: <<-SHELL
	# 		echo "Worker provisioned, starting worker script"
	# 	SHELL
	# 	serverworker.vm.provision "shell", path: "scripts/worker.sh", args: [WORKER_IP]
	# end
end
