
SERVER_NAME = "lpeggyS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "lpeggySW"
WORKER_IP =  "192.168.56.111"
BROADCAST_IP = "192.168.56.255"


server_script = <<-SHELL
    apk add curl
    export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=#{SERVER_IP} --advertise-address=#{SERVER_IP} --node-ip=#{SERVER_IP} --flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh -
    echo "Sleeping for 5 seconds to wait for k3s to start"
	sleep 5

	echo "Waiting for k3s token to be created..."
	while [ ! -f /var/lib/rancher/k3s/server/token ]; do
		sleep 2
	done
    cp /var/lib/rancher/k3s/server/token /vagrant
    cp /etc/rancher/k3s/k3s.yaml /vagrant
	ifconfig eth1 broadcast #{BROADCAST_IP}
    SHELL

worker_script = <<-SHELL
    apk add curl
    export K3S_TOKEN_FILE="/vagrant/token"
    export INSTALL_K3S_EXEC="agent --server https://#{SERVER_IP}:6443 --node-ip=#{WORKER_IP} --flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh -
	ifconfig eth1 broadcast #{BROADCAST_IP}
    SHELL


Vagrant.configure(2) do |config|
	config.vm.box = "generic/alpine314"
	config.vm.box_url = "https://app.vagrantup.com/generic/boxes/alpine318"

	config.vm.define SERVER_NAME, primary: true do |server|
		server.vm.network "private_network", ip: SERVER_IP
		server.vm.synced_folder "./tmp", "/vagrant", create: true
		server.vm.hostname = SERVER_NAME
		server.vm.provider "virtualbox" do |v|
			v.cpus = 1
			v.memory = 1024
			v.name = SERVER_NAME
		end

		# Run server setup script
		server.vm.provision "shell", privileged: true, inline: server_script

		# Copy SSH keys from the host to the guest machine
		server.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		server.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
		# Run the setup_ssh.sh script
		server.vm.provision "shell", path: "scripts/setup_ssh.sh"
	end

	config.vm.define WORKER_NAME do |serverworker|
		serverworker.vm.network "private_network", ip: WORKER_IP
		serverworker.vm.synced_folder "./tmp", "/vagrant"
		serverworker.vm.hostname = WORKER_NAME
		serverworker.vm.provider "virtualbox" do |v|
			v.cpus = 1
			v.memory = 1024
			v.name = WORKER_NAME
		end

		# Run worker setup script
		serverworker.vm.provision "shell", privileged: true, inline: worker_script

		# Copy SSH keys from the host to the guest machine
		serverworker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		serverworker.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
		# Run the setup_ssh.sh script
		serverworker.vm.provision "shell", path: "scripts/setup_ssh.sh"

		# When worker is up, remove k3s token file from host machine
		serverworker.trigger.after :up do |trigger|
            trigger.run = {inline: "rm tmp/token"}
        end
	end
end
