apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  type: ClusterIP
  selector:
    # app.kubernetes.io/name: app-two
    app: app-two
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080