apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  type: ClusterIP
  selector:
    # app.kubernetes.io/name: app-one
    app: app-one
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080