apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/my-new-repo.git
    targetRevision: HEAD
    path: wil42
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
